// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.9.176
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandTaskRunner
{
    static class Vsix
    {
        public const string Id = "fc1aafb2-321e-41bd-ac37-03b09ea8ef31";
        public const string Name = "Command Task Runner";
        public const string Description = "Adds support for command line batch files in Visual Studio 2015's Task Runner Explorer. Supports .cmd, .bat, .ps1 and .psm1 files.";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "command-line, PowerShell, cmd, batch, bat, exe";
    }
}
