// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandTaskRunner
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddCommandPackageString = "bc2a198c-4598-4e8f-97a6-249573ca88a9";
        public static Guid guidAddCommandPackage = new Guid(guidAddCommandPackageString);

        public const string guidAutoloadString = "e1ce9b3d-25f9-41ef-a3bd-702f05900f58";
        public static Guid guidAutoload = new Guid(guidAutoloadString);

        public const string guidCommandCmdSetString = "1b181a1d-76a0-4629-8e2a-8c24d86c29bd";
        public static Guid guidCommandCmdSet = new Guid(guidCommandCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddCommandId = 0x0064;
    }
}